### PR TITLE
Fix condition handling of gateways and routes

### LINKED ISSUE #277: Set status condition on HTTPRoute resources
Need to state different kind of reasons when a route is accepted but configs are invalid inside.

### PR DESCRIPTION
**Pull request by solmonk**
**What type of PR is this?**

bug

**Which issue does this PR fix**:

Follow-up to a fix of #282 - also partially fixes #277 

**What does this PR do / Why do we need it**:

Total rework of conditions update - now conditions are handled individually, and got rid of infinite loop and missing updates

**If an issue # is not available please add repro steps and logs from aws-gateway-controller showing the issue**:

**Testing done on this change**:

**Automation added to e2e**:

**Will this PR introduce any new dependencies?**:

**Will this break upgrades or downgrades. Has updating a running cluster been tested?**:

**Does this PR introduce any user-facing change?**:

```release-note

```

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: controllers/gateway_controller.go [hunk 1]
```diff
@@ -258,21 +256,15 @@ func (r *GatewayReconciler) cleanupGatewayResources(ctx context.Context, gw *gat
 
 func (r *GatewayReconciler) updateGatewayStatus(ctx context.Context, serviceNetworkStatus *latticestore.ServiceNetwork, gw *gateway_api.Gateway) error {
 
-	glog.V(6).Infof("updateGatewayStatus: updating last transition time \n")
```
Comment (liwenwu-amazon) [inline controllers/gateway_controller.go:261]: can we leave this for debugging?

**Review by liwenwu-amazon — APPROVED** [review]
LGTM, had some minor comments that we should keep some debugging msgs for trouble shooting.

File: controllers/gateway_controller.go (hunk 1 above)
Comment (solmonk) [reply controllers/gateway_controller.go:261]: updateGatewayStatus is only called in a single place and there is a log beforehand, so it is a duplicate IMO
