### PR TITLE
Remove assumption of default namespaces in httproutes

### LINKED ISSUE #244: bug: Target not automatically registered in Target Group
I am seeing errors like this in gateway api controller logs and the target is not automatically registered in target group

```
E0511 21:55:34.435754       1 request.go:539] Failed request: VpcLattice/ListTargets, Payload: {  TargetGroupIdentifier: ""}, Error: InvalidParameter: 1 validation error(s) found.
93
- minimum field size of 17, ListTargetsInput.TargetGroupIdentifier.
```

Please advise, will provide more info upon request.

P/S: I've already created a support ticket in AWS (Case ID 12717202271), posting this here for visibility.

### PR DESCRIPTION
**Pull request by solmonk**
**What type of PR is this?**
bug

**Which issue does this PR fix**:
Fixes #244 #251 

**What does this PR do / Why do we need it**:
Will remove reference of hardcoded "default" and use its own namespace whenever it needs inference

**If an issue # is not available please add repro steps and logs from aws-gateway-controller showing the issue**:

**Testing done on this change**:
* `make e2etest`
* pending gw conformance test

**Automation added to e2e**:
Will add e2etest in a separate PR.

**Will this PR introduce any new dependencies?**:

**Will this break upgrades or downgrades. Has updating a running cluster been tested?**:

**Does this PR introduce any user-facing change?**:

```release-note

```

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: test/pkg/test/framework.go [hunk 1]
```diff
@@ -86,7 +89,7 @@ func NewFramework(ctx context.Context) *Framework {
 	SetDefaultEventuallyTimeout(180 * time.Second)
 	SetDefaultEventuallyPollingInterval(10 * time.Second)
 	BeforeEach(func() { framework.ExpectToBeClean(ctx) })
-	AfterEach(func() { framework.ExpectToBeClean(ctx) })
+	AfterEach(func() { framework.CleanTestEnvironment(ctx); framework.ExpectToBeClean(ctx) })
```
Comment (liwenwu-amazon) [inline test/pkg/test/framework.go:92]: Please revert this change.  We purposely do it as `pause on failure` and keep all lattice resource(s), so that we can debug in case of failure!

Comment (solmonk) [reply test/pkg/test/framework.go:92]: This was included totally by mistake, I will remove it.

**Comment by solmonk** [comment]
Used `inventory-ver1.yaml` (in non-default), `my-hotel-gateway.yaml` (in default) and the following httproute (in non-default):
```
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: inventory
spec:
  parentRefs:
  - name: my-hotel
    namespace: default
    sectionName: http
  rules:
  - backendRefs:
    - name: inventory-ver1
      kind: Service
      port: 8090
      weight: 10
```
Confirmed that target groups are created with correct name including non-default, and targets are registered.

File: pkg/deploy/lattice/listener_synthesizer.go [hunk 2]
```diff
@@ -65,9 +66,8 @@ func (l *listenerSynthesizer) Synthesize(ctx context.Context) error {
 
 		glog.V(6).Infof("ListenerSynthesize >>>> delete staled sdk listener %v\n", *sdkListener)
 		l.listener.Delete(ctx, sdkListener.ListenerID, sdkListener.ServiceID)
-		k8sname, k8snamespace := latticeName2k8s(sdkListener.Name)
 
-		l.latticestore.DelListener(k8sname, k8snamespace, sdkListener.Port, sdkListener.Protocol)
+		l.latticestore.DelListener(sdkListener.Name, sdkListener.Namespace, sdkListener.Port, sdkListener.Protocol)
```
Comment (liwenwu-amazon) [inline pkg/deploy/lattice/listener_synthesizer.go:70]: I do not think sdkListener.Namespace is populated by l.getSDKListeners().  Not sure why unit test did not catch this? Also, i think the e2e should catch this too. (not sure why )

Comment (liwenwu-amazon) [reply pkg/deploy/lattice/listener_synthesizer.go:70]: can u confirm this from the debugging output at line#58

Comment (liwenwu-amazon) [reply pkg/deploy/lattice/listener_synthesizer.go:70]: Also,  for all these xxxSDKxxx() routine(s), I think we should use the name or tags return from lattice to figure out the namespace.

Comment (solmonk) [reply pkg/deploy/lattice/listener_synthesizer.go:70]: I made the change to that function just right below actually, I think it is working?

On listener creation:
```
I0519 15:20:51.334060   39938 listener_synthesizer.go:126] getSDKListeners result >> [0xc00090cf50]
I0519 15:20:51.334069   39938 listener_synthesizer.go:58] getSDKlistener: [0xc00090cf50], err: <nil>
I0519 15:20:51.334074   39938 listener_synthesizer.go:86] findMatchListener: found matching moduleListener &{{0xc000a59280 AWS::VPCServiceNetwork::Listener inventory-non-default-80-HTTP} {inventory non-default 80 HTTP {false inventory-ver1 non-default}} <nil>}
```

**Comment by liwenwu-amazon** [comment]
Also, please update or add unit test(s).

File: pkg/deploy/lattice/listener_synthesizer.go (hunk 2 above)
Comment (liwenwu-amazon) [reply pkg/deploy/lattice/listener_synthesizer.go:70]: The objective of these xxxSDKxxx() is to figure out if Lattice resource(s) can map back to K8S resource.  It should `not` imply nor inherent any value from K8S object.

Comment (solmonk) [reply pkg/deploy/lattice/listener_synthesizer.go:70]: It is impossible to figure out exact namespace because of the naming scheme of lattice and k8s. Lets say we have lattice listener `a-b-c-d-e-80-HTTP`, the resource can be either one of:
`a/b-c-d-e`
`a-b/c-d-e`
`a-b-c/d-e`
`a-b-c-d/e`
I think we need to rely on k8s information to figure out namespace. it should be the same as the lattice service anyways.

Comment (liwenwu-amazon) [reply pkg/deploy/lattice/listener_synthesizer.go:70]: then we need to explicit using `tag`.  The whole idea is to compare between lattice resources and K8S object(s).  And perform cleanup lattice resources if they are not matching K8S objects.  

If we start infer lattice resource(s) from K8S object(s), we will end up leaking more lattice resource(s)

File: controllers/gateway_controller.go [hunk 3]
```diff
@@ -149,7 +150,7 @@ func (r *GatewayReconciler) reconcile(ctx context.Context, req ctrl.Request) err
 					continue
 				}
 				gwName := types.NamespacedName{
-					Namespace: httpRoute.Namespace,
+					Namespace: gw.Namespace,
```
Comment (liwenwu-amazon) [inline controllers/gateway_controller.go:153]: this needs to be `httpRoute.Spec.ParentRefs[0].Namespace`  if exist, or default to httpRoute.Namespace

Comment (liwenwu-amazon) [reply controllers/gateway_controller.go:153]: We need a e2e to cover this

**Review by liwenwu-amazon — APPROVED** [review]
